# Site settings
title: WebKitGTK
baseurl:
  "" # the subpath of your site, e.g. /blog/
  # usually empty. necessary for building absolute URIs
  # for metadata header
url: "https://webkitgtk.org" # the base hostname & protocol for your site
sourceurl: "https://github.com/WebKitGTK/webkitgtk.org" # "edit this website" link in the footer
description: "A WebKit port for the GTK library."
issuesurl: "https://github.com/WebKitGTK/webkitgtk.org/issues" # issue tracker for website
permalink: /:title/
primary-color: "#26a269" #used in ios theme. further color customization in style.css

# Build settings
markdown: kramdown
